### ISSUE TITLE
Supported versions of node not documented

### ISSUE THREAD

**Issue by hughrawlinson** [EvanBurchard/wish#6]
Wish doesn't work on Node v7.5.0 - I think Node changed the Error format and now the regex [here](https://github.com/EvanBurchard/wish/blob/master/lib/wish.js#L76) doesn't match. This issue could be resolved by either fixing the regex or by [specifying engines in package.json](https://docs.npmjs.com/files/package.json#engines).

Great library, awesome book! Thanks!

**Comment by EvanBurchard** [comment]
Hey. Thanks for letting me know. @blrobin2 was kind enough to submit a PR with a better regex but setting a minimum version is a really nice touch, so I added it. 

Thanks again, and happy reading!
